image: node:latest

# This folder is cached between builds
# https://docs.gitlab.com/ee/ci/yaml/index.html#cache
cache:
  paths:
    - node_modules/

stages:
  - build
  - preview
  - production

build:
  except:
    - /^\d+\.\d+-.*$/
  stage: build
  artifacts:
    paths:
      - dist/
  script:
    - npm install
    - npm run build
deploy:
  only: 
    - main
    - develop
    - /^\d+\.\d+\.\d+$/
    - /^\d+\.\d+$/
  stage: production
  environment:
    name: production
    url:  $PROD_URL
  dependencies:
    - build
  variables:
    CLOUDFLARE_ACCOUNT_ID: $CLOUDFLARE_ACCOUNT_ID
    CLOUDFLARE_API_TOKEN: $CLOUDFLARE_API_TOKEN
    CF_ZONE_ID: $CLOUDFLARE_ZONE_ID
    CLOUDFLARE_PROJECT_NAME: $CLOUDFLARE_PROJECT_NAME
  script:
    - env
    - npx wrangler pages deploy ./dist --branch dev --project-name $CLOUDFLARE_PROJECT_NAME

release:
  only: 
    - main
    - /^\d+\.\d+\.\d+$/
    - /^\d+\.\d+$/
  stage: production
  when: manual
  environment:
    name: production
    url:  $PROD_URL
  dependencies:
    - build
  variables:
    CLOUDFLARE_PROJECT_NAME: $CLOUDFLARE_PROJECT_NAME
    CLOUDFLARE_API_TOKEN:   $CLOUDFLARE_API_TOKEN
    CLOUDFLARE_ACCOUNT_ID:  $CLOUDFLARE_ACCOUNT_ID
  script:
    - CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID npx wrangler pages deploy ./dist --project-name $CLOUDFLARE_PROJECT_NAME

